name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build docker image
        run: docker build -t sejalzend/github-actions-demo:latest .
      - name : Push to dockerhub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/github-actions-demo